# Generated by Django 5.2.5 on 2025-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employees',
            field=models.IntegerField(default=0),
        ),
    ]
