# Generated by Django 5.2.5 on 2025-09-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_client_employees'),
        ('ruralapp', '0008_organization_order_client_org_order_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ruralapp.membership',),
        ),
        migrations.CreateModel(
            name='OrganizationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ruralapp.organization',),
        ),
    ]
