# Generated by Django 4.2 on 2023-04-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galpon', models.IntegerField(default=1)),
                ('location', models.CharField(choices=[('M0', 'Modulo 0'), ('M1', 'Modulo 1'), ('M2', 'Modulo 2'), ('M3', 'Modulo 3'), ('M4', 'Modulo 4'), ('M5', 'Modulo 5'), ('CF1', 'Corta Fuego 1'), ('CF2', 'Corta Fuego 2'), ('CF3', 'Corta Fuego 3'), ('CF4', 'Corta Fuego 4'), ('CF5', 'Corta Fuego 5')], max_length=3)),
                ('zona', models.CharField(blank=True, choices=[('A', 'Lado A'), ('B', 'Lado B')], max_length=1)),
                ('area', models.CharField(blank=True, choices=[('PTAL', 'Parte alta'), ('PTBA', 'Parte baja'), ('PSCA', 'Pasillo caliente'), ('PSFR', 'Pasillo frio'), ('PSFI', 'Pasillo filtro')], max_length=4)),
                ('tarea', models.CharField(choices=[('Sop', 'Soplado'), ('Asp', 'Aspirado'), ('Lav', 'Lavado')], default=None, max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
