# Generated by Django 4.2 on 2023-04-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_usuario1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_usuario2', to=settings.AUTH_USER_MODEL)),
                ('usuario3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_usuario3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
