# Generated by Django 4.2 on 2023-04-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_guardia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='usuario1',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Tecnico 1'}, on_delete=django.db.models.deletion.CASCADE, related_name='usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='usuario2',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Tecnico 2'}, on_delete=django.db.models.deletion.CASCADE, related_name='usuario2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='usuario3',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'IT'}, on_delete=django.db.models.deletion.CASCADE, related_name='usuario3', to=settings.AUTH_USER_MODEL),
        ),
    ]
