# Generated by Django 4.1.7 on 2023-04-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_sorteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='cantidad_ganadores',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sorteo')),
            ],
        ),
    ]
