# Generated by Django 4.1.7 on 2023-12-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_alter_sorteo_cantidad_ganadores_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sorteos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='participantes',
            field=models.ManyToManyField(related_name='sorteos_participados', to=settings.AUTH_USER_MODEL),
        ),
    ]
