# Generated by Django 4.1.7 on 2023-12-12 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_sorteo_user_alter_sorteo_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='user',
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
