# Generated by Django 4.1.7 on 2024-09-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_sorteo_user_alter_sorteo_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='hora_fin',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='hora_inicio',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='total_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
