# Generated by Django 4.1.7 on 2024-11-14 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_guardia_hora_fin_guardia_hora_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('total_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('justificar', models.TextField(max_length=500)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('feedback_admin', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
