# Generated by Django 4.1.7 on 2024-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_horaextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='es_guardia',
            field=models.BooleanField(default=False),
        ),
    ]
