# Generated by Django 4.1.7 on 2025-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_horaextra_es_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='porcent',
            field=models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('100%', '100%')], default='50%', max_length=4),
        ),
    ]
