# Generated by Django 5.1.6 on 2025-05-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_horaextra_aprobado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='usuario1',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Operaciones'}, on_delete=django.db.models.deletion.CASCADE, related_name='usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='usuario2',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Mantenimiento'}, on_delete=django.db.models.deletion.CASCADE, related_name='usuario2', to=settings.AUTH_USER_MODEL),
        ),
    ]
