"""
Django settings for djangocrud project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from django.conf.locale.es import formats as es_formats
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(oa(omhdw75#3qzk_p-6zfdfmvj#%tn=oci!ww+ssog(ib%-o='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['127.0.0.1', '10.45.0.69', 'localhost', '200.123.250.250', 'lapp-arg01.binfra.ca']
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# ALLOWED_HOSTS = os.environ.get[("DJANGO_ALLOWED_HOSTS")]

CSRF_TRUSTED_ORIGINS = ['https://lapp-arg01.binfra.ca']

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'bootstrap_datepicker_plus',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # "debug_toolbar",
    'tasks',
    'management',
    # 'tools',
    # 'formus',
    'ruralapp',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    #'django_celery_beat',
    #'django_celery_results',
    #'pwa',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"
HANDLER403 = 'myapp.views.error_403'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #"debug_toolbar.middleware.DebugToolbarMiddleware",
    'djangocrud.restrict_access_middleware.RestrictAccessMiddleware',
]

ROOT_URLCONF = 'djangocrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["djangocrud/templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangocrud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#    "default": {
#        "ENGINE": 'django.db.backends.postgresql_psycopg2',
#        "NAME": "postgres",
#        "USER": "postgres",
#        "PASSWORD": "root",
#        "HOST": "localhost",
#        "PORT": "5432",
#    }
# }


DATABASES = {
   "default": {
       "ENGINE": 'django.db.backends.postgresql_psycopg2',
       "NAME": "postgres",
       "USER": "admin",
       "PASSWORD": "btf.1234",
       "HOST": "localhost",
       "PORT": "5432",
   }
}

# DATABASES = {
#     "default": {
#         "ENGINE": 'django.db.backends.postgresql_psycopg2',
#         "NAME": os.environ.get("SQL_DATABASE"),
#         "USER": os.environ.get("SQL_USER"),
#         "PASSWORD": os.environ.get("SQL_PASSWORD"),
#         "HOST": os.environ.get("SQL_HOST"),
#         "PORT": os.environ.get("SQL_PORT"),
#     }
# }



# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }



# DATABASES = {
#     "default": {
#         "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
#         "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
#         "USER": os.environ.get("SQL_USER", "user"),
#         "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
#         "HOST": os.environ.get("SQL_HOST", "localhost"),
#         "PORT": os.environ.get("SQL_PORT", "5432"),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

#AUTH_USER_MODEL = 'tasks.CustomUser'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-AR'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
DATE_INPUT_FORMATS = ['%d/%m/%Y']
CRISPY_DATE_FORMAT = 'dd/mm/yyyy'
USE_L10N = True
USE_TZ = True
es_formats.DATE_FORMAT = '%d/%m/%Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = BASE_DIR / 'static'
#STATIC_ROOT =  '/static/'


LOGIN_URL = '/signin'
LOGIN_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 


INTERNAL_IPS = ["127.0.0.1",]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Celery configuration
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'America/Argentina/Buenos_Aires'
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
# # Configuración del backend de resultados
# CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
# CELERY_RESULT_EXTENDED = True
# # Opcional: Configuración para evitar almacenar resultados de tareas exitosas
# CELERY_TASK_IGNORE_RESULT = False



# PWA_APP_NAME = "LAPP"
# PWA_APP_DESCRIPTION = "Látigo App"
# PWA_APP_THEME_COLOR = "#383580"
# PWA_APP_THEME_BACKGROUND_COLOR = "#8C9BFF"

# PWA_APP_ICONS = [
#     {
#     "src": "/media/Lapp_Icono.png",
#     "sizes": "160x160"
#     }
# ]

# PWA_APP_ICONS_APPLE = [
#     {
#     "src": "/media/Lapp_Icono.png",
#     "sizes": "160x160"
#     }
# ]