# Generated by Django 4.1.7 on 2024-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0002_appstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appstate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appstate',
            name='last_week_advance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appstate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
