# Generated by Django 5.1.6 on 2025-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeat_for_week',
            field=models.BooleanField(default=False),
        ),
    ]
