# Generated by Django 5.1.6 on 2025-05-27 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0005_order_repeat_for_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
