# Generated by Django 5.2.4 on 2025-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0006_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='User allowed to administrate business'),
        ),
    ]
