# Generated by Django 5.2.5 on 2025-09-23 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0007_userprofile_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CLIENT', 'Client')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'is_active'], name='ruralapp_or_type_331b34_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='ruralapp.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_orders', to='ruralapp.organization'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GESTION', 'Restaurant - Gestión'), ('COCINA', 'Restaurant - Cocina'), ('DELIVERY', 'Restaurant - Delivery'), ('CLIENT_ADMIN', 'Client - Admin'), ('CLIENT_USER', 'Client - User')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ruralapp.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'role', 'is_active'], name='ruralapp_me_organiz_24b9fc_idx'), models.Index(fields=['user', 'is_active'], name='ruralapp_me_user_id_ffc05d_idx')],
                'unique_together': {('user', 'organization', 'role')},
            },
        ),
    ]
