# Generated by Django 5.2.5 on 2025-09-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruralapp', '0008_organization_order_client_org_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
